### ISSUE TITLE
Header images: are blurry resolution seems not be big enough

### ISSUE THREAD

**Issue by b-g** [DigitalDesignIO/dmd-website#2]
e.g. https://digitalmediadesign.io/assets/images/hero-3-lg.jpg should be 1920 x 960 but isn't. Please double check, in doubt ask Markus for high res images

**Comment by Andi-Lo** [comment]
The image was resized from a 3000x2000 source file. I re did it again but I am not sure if there is a huge difference.

**Comment by b-g** [comment]
Ok + thanks! Did you use _Bicubic Sharper (reduction)_ in Psd?
