### ISSUE TITLE
Chart Aufbau des Studiums: "Design 4" is missing

### ISSUE THREAD

**Issue by b-g** [DigitalDesignIO/dmd-website#3]
"Design 4" seems to be missing ... doesn't make sense as it is now

![screen shot 2016-05-06 at 09 55 38](https://cloud.githubusercontent.com/assets/480224/15067470/ede0e530-1370-11e6-96aa-643a409891d6.png)

**Comment by Andi-Lo** [comment]
Maybe @KlemensEhret knows if this is intended or not. I did not add the content to the time table so I can not tell you.

**Comment by KlemensEhret** [comment]
Hallo Benedikt,
hallo Andreas,

habe den Timetable geändert.

Du kannst das auch tun via kirby.

Sonst schauen wir uns das nächste Woche an, wenn wir uns sehen.

Gruß
Klemens

Am 06.05.2016 um 12:55 schrieb Andreas Lorer:
