### ISSUE TITLE
Add the two best prog. entwerfen. documentations to /project section

### ISSUE THREAD

**Issue by b-g** [DigitalDesignIO/dmd-website#7]
http://dl.dropbox.com/u/2700930/Prog.%20Entwerfen.%20Best%20of%20Dokus.zip
(please create a nice thumbnail image on your own, or the students to do so)

Thanks!

**Comment by Andi-Lo** [comment]
Just to keep you updated on this one: 
I am working on a complete overhaul of the project site so we can mirror the generators documentation structure 1 to 1.

For now ~90% is done and there is just some formatting and css styling left to do.

What is completely missing is the functionality to implement the p5 js iframes. I don't have a solution to that jet and I am not sure how long it will take until I find one that works out decently.

I could add the missing content from "Prog. Entwerfen" the next days but leave out the p5 content so the projects are at least online.

Thoughts?

**Comment by b-g** [comment]
OK + thanks for the update. A link to the documentations would have been enough for me ... but an integration into the CMS is of course very nice too.

The p5 content is important, please add them too. It is quite straight forward, see https://github.com/DigitalDesignIO/dmd-documenation-generator/blob/master/src/components/PageItemP5.react.js#L35

``` js
    var iframe = $(...)[0];
    var userScript = iframe.contentWindow.document.createElement('script');
    userScript.type = 'text/javascript';
    userScript.text = "new p5();\n" + content_of_p5js_file;
    userScript.async = false;
    iframe.contentWindow.document.body.appendChild(userScript);
   ...
   // you might want to use the iframe.onLoad to check if the p5 script was loaded
```

Best, B

**Comment by Andi-Lo** [comment]
Hm, I tried and debugged now for 4 long hours but can not get it working with this approach. 
He does not let me write simple javascript code into the iframe. No solution on stackoverflow is working either :(

**Comment by b-g** [comment]
Odd. Works out of the box in react ... I "stole" it from https://github.com/processing/p5.js-website/blob/master/js/examples.js#L133 ... please check. Best, B

**Comment by Andi-Lo** [comment]
Thats my code:

```
<div class="col-sm-7 middle-col col-sm-offset-3">

  <?php $iframeUID = uniqid(); ?>
  <iframe id="<?php echo ($iframeUID) ?>" width="100%" height="500" src="<?php echo url('assets/p5/p5-iframe-template.html'); ?>"></iframe>

  <script> 
    var iframe = document.getElementById("<?php echo ($iframeUID) ?>");

    iframe.onload = function() {
      var userScript = iframe.contentWindow.document.createElement('script');
      userScript.type = 'text/javascript';
      console.log(userScript);
      userScript.text = '<?php echo(($content->pfile()->toFile()->content())) ?>';
      userScript.async = false;
      iframe.contentWindow.document.body.appendChild(userScript);
    };
  </script>
</div>

<div class="col-sm-2 caption">
  <p><?php echo $content->caption()->kirbytextRaw() ?></p>
</div>
```

But it is not working. I get either a blank canvas or I get a javascript error when I assign the content of the p5.js file to the variable.

I created a post on stackoverflow maybe someone could help me there:
http://stackoverflow.com/questions/37727875/refreshing-an-iframe-after-adding-a-javascript-file

Maybe we should meet up on this one and try to find (maybe a different solution) ?

**Comment by b-g** [comment]
Ok! But I think there is a line missing `userScript.text = 'new p5();\n';` ... try this:

```
...
userScript.type = 'text/javascript';
userScript.text = 'new p5();\n';
console.log(userScript);
userScript.text += '<?php echo(($content->pfile()->toFile()->content())) ?>';
...
```

**Comment by Andi-Lo** [comment]
You are right I am missing that line for now. I have to find another way of adding that string to the file. Maybe when the user uploads it with Kirby.

One guy on stackoverflow got me a solution for adding the script to the iframe. However the `new p5()`  is not working out when I attach it via: `userScript.text = 'new p5();\n';`

**Comment by b-g** [comment]
I assume the loaded iframe has a source html which includes p5.js? 

See:
1. html to be loaded to the iframe, [check your source attribute ... line 55](https://github.com/DigitalDesignIO/dmd-documenation-generator/blob/08232e0b1695272957552895907323610ab3ac76/src/components/PageItemP5.react.js#L55)
2. [p5-iframe-template.html](https://github.com/DigitalDesignIO/dmd-documenation-generator/blob/08232e0b1695272957552895907323610ab3ac76/lib/p5/p5-iframe-template.html)

**Comment by Andi-Lo** [comment]
I got all bugs and issues figured out and that feature is finally done and the projects are all in the generator format and online for viewing. See: https://digitalmediadesign.io/#Projekte

I hope I never have to work with iframes again XD

**Comment by b-g** [comment]
👍 Many thanks + amen!
