### ISSUE TITLE
Wrong format for headline 'Studium – Aufbau des Studiums'

### ISSUE THREAD

**Issue by b-g** [DigitalDesignIO/dmd-website#8]
https://digitalmediadesign.io/#Studium
"Studium" should be bold ... but isn't

![screen shot 2016-05-23 at 08 56 29](https://cloud.githubusercontent.com/assets/480224/15462677/9d9c37da-20c4-11e6-9d3c-dc1621122daf.png)

**Comment by Andi-Lo** [comment]
thanks for spotting this one
